### ISSUE TITLE
where to find pre-trained model

### ISSUE THREAD

**Issue by vkmavani** [adeboissiere/FUSION-human-action-recognition#6]
file : FUSION-human-action-recognition/notebooks/0.0-amdb-Tutorial.ipynb

# Global variables
model_folder = os.getcwd() + '/../' \
                           + 'models/' \
                           + 'fusion_test_tube_seed=0/' \
                           + 'fusion_20/' \
                           + 'cross_subject/' \
                           + 'aug=True/' 

model_file = 'model12.pt'

use_pose = True
use_ir = True

**Comment by adeboissiere** [comment]
My bad I haven't included the pretrained models with the repo. I'll upload them will comment back once this is done.

**Comment by adeboissiere** [comment]
Hello, 
You can find the pretrained models here: https://etsmtl365-my.sharepoint.com/:f:/g/personal/alban_main-de-boissiere_1_ens_etsmtl_ca/EkE2Uzx0YTtFlPZbY4mZvQYBfYPDL-RoLkgO6584aKmnlg?e=sy45Ab

**Comment by vkmavani** [comment]
> Hello,
> You can find the pretrained models here: https://etsmtl365-my.sharepoint.com/:f:/g/personal/alban_main-de-boissiere_1_ens_etsmtl_ca/EkE2Uzx0YTtFlPZbY4mZvQYBfYPDL-RoLkgO6584aKmnlg?e=sy45Ab

Thank you very very much...
